const PRODUCTOS = [
  { cod: 'ABA-01', nombre: 'CHOCOLATE DE TAZA ORO DE CUSCO 80GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 50, precio_caja: 45, precio_unitario: 0.9 },
  { cod: 'ABA-02', nombre: 'ARROZ COSTEÑO EXTRA GRANEADO 750GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 20, precio_caja: 67, precio_unitario: 3.35 },
  { cod: 'ABA-03', nombre: 'AZUCAR DULFINA 1KG', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 10, precio_caja: 35, precio_unitario: 3.5 },
  { cod: 'ABA-04', nombre: 'ACEITE PRIMOR 900ML', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 95, precio_unitario: 7.92 },
  { cod: 'ABA-05', nombre: 'ACEITE CIL 900 ML', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 89.7, precio_unitario: 7.47 },
  { cod: 'ABA-06', nombre: 'LENTEJA COSTEÑO 500GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 55.7, precio_unitario: 4.64 },
  { cod: 'ABA-07', nombre: 'ARVEJA PARTIDA COSTEÑO 500GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 36.3, precio_unitario: 3.02 },
  { cod: 'ABA-08', nombre: 'FIDEO NICOLINI SOPAS 225GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 20, precio_caja: 22, precio_unitario: 1.1 },
  { cod: 'ABA-09', nombre: 'FIDEO NICOLINI SPAGUETTI 450GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 20, precio_caja: 42, precio_unitario: 2.1 },
  { cod: 'ABA-10', nombre: 'MERMELADA DE FRESA FANNY 90GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 108, precio_caja: 164.16, precio_unitario: 1.52 },
  { cod: 'ABA-11', nombre: 'MERMELADA DE FRESA FANNY 227GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 46.92, precio_unitario: 3.91 },
  { cod: 'ABA-12', nombre: 'AVENA 3 OSITOS 110GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 24, precio_caja: 17.4, precio_unitario: 0.72 },
  { cod: 'ABA-13', nombre: 'CACAO 100% DE TAZA SOL DEL CUSCO', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 115, precio_unitario: 9.58 },
  { cod: 'ABA-14', nombre: 'CHOCOLATE DE TAZA SOL DEL CUSCO 90GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 50, precio_caja: 103, precio_unitario: 2.06 },
  { cod: 'ABA-16', nombre: 'LENTEJA PAISANA 500GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 52.8, precio_unitario: 4.4 },
  { cod: 'ABA-17', nombre: 'MERMELADA DE FRESA FANNY POTE 320GR', proveedor: 'Grazy', categoria: 'Abarrotes', caja: 12, precio_caja: 54.5, precio_unitario: 4.54 },
  { cod: 'CHO-01', nombre: 'FERRERO ROCHER T4', proveedor: 'Grazy', categoria: 'Chocolates y dulces', caja: 10, precio_caja: 96, precio_unitario: 9.6 },
  { cod: 'CHO-02', nombre: 'HERSHEY DOYBAG NUGGET 120GR', proveedor: 'Grazy', categoria: 'Chocolates y dulces', caja: 12, precio_caja: 172.5, precio_unitario: 14.38 },
  { cod: 'CHO-03', nombre: 'BOLSA CHOCO MINIS SNCK MWAY TWIX 3M 235G', proveedor: 'Perufarma', categoria: 'Chocolates y dulces', caja: 8, precio_caja: 154.8, precio_unitario: 19.35 },
  { cod: 'CHO-04', nombre: 'TOBLERONE BAG TINY DARK SEA 200G', proveedor: 'Perufarma', categoria: 'Chocolates y dulces', caja: 20, precio_caja: 448.0, precio_unitario: 22.4 },
  { cod: 'CHO-05', nombre: 'TOBLERONE MILK 100G', proveedor: 'Perufarma', categoria: 'Chocolates y dulces', caja: 20, precio_caja: 182.0, precio_unitario: 9.1 },
  { cod: 'CHO-06', nombre: 'TOBLERONE DARK 100G', proveedor: 'Perufarma', categoria: 'Chocolates y dulces', caja: 20, precio_caja: 182.0, precio_unitario: 9.1 },
  { cod: 'CHO-07', nombre: 'MILKA ALPINE MILK 90G', proveedor: 'Perufarma', categoria: 'Chocolates y dulces', caja: 25, precio_caja: 210.0, precio_unitario: 8.4 },
  { cod: 'CHO-08', nombre: 'SKITTLES ORIGINAL SINGLES CANDY X 204 GR', proveedor: 'Perufarma', categoria: 'Chocolates y dulces', caja: 12, precio_caja: 100.56, precio_unitario: 8.38 },
  { cod: 'CON-01', nombre: 'ATUN FILETE FLORIDA 140GR', proveedor: 'Grazy', categoria: 'Conservas', caja: 48, precio_caja: 221, precio_unitario: 4.6 },
  { cod: 'CON-02', nombre: 'ATUN FILETE PRIMOR 140GR', proveedor: 'Grazy', categoria: 'Conservas', caja: 48, precio_caja: 212, precio_unitario: 4.42 },
  { cod: 'CON-03', nombre: 'DURAZNO ACONCAGUA 822GR', proveedor: 'Grazy', categoria: 'Conservas', caja: 12, precio_caja: 92, precio_unitario: 7.67 },
  { cod: 'CON-04', nombre: 'DURAZNO ARICA 820GR', proveedor: 'Grazy', categoria: 'Conservas', caja: 12, precio_caja: 75, precio_unitario: 6.25 },
  { cod: 'CON-05', nombre: 'TROZOS DE ATUN PRIMOR 140GR', proveedor: 'Grazy', categoria: 'Conservas', caja: 48, precio_caja: 203, precio_unitario: 4.23 },
  { cod: 'EMP-01', nombre: 'CAJA NAVIDEÑA 1A CON PRECINTO', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 4, precio_unitario: 4 },
  { cod: 'EMP-02', nombre: 'CAJA NAVIDEÑA 1B CON PRECINTO', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 4.5, precio_unitario: 4.5 },
  { cod: 'EMP-03', nombre: 'CAJA NAVIDEÑA 2A CON PRECINTO', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 4.2, precio_unitario: 4.2 },
  { cod: 'EMP-04', nombre: 'CAJA NAVIDEÑA 2B CON PRECINTO', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 5.5, precio_unitario: 5.5 },
  { cod: 'EMP-05', nombre: 'CAJA NAVIDEÑA 3 CON PRECINTO', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 6.5, precio_unitario: 6.5 },
  { cod: 'EMP-06', nombre: 'CANASTA DE PLASTICO TIPO YUTE N°30', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 17.5, precio_unitario: 17.5 },
  { cod: 'EMP-07', nombre: 'CESTO DE PLASTICO N°40', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 31.5, precio_unitario: 31.5 },
  { cod: 'EMP-08', nombre: 'CESTO DE PLASTICO TIPO YUTE N°40', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 21.9, precio_unitario: 21.9 },
  { cod: 'EMP-09', nombre: 'CAJA ORGANIZADORA C/RUEDAS N°60', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 21.5, precio_unitario: 21.5 },
  { cod: 'EMP-10', nombre: 'CAJA ORGANIZADORA C/RUEDAS N°25', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 12.5, precio_unitario: 12.5 },
  { cod: 'EMP-11', nombre: 'CAJA ORGANIZADORA NAVIDEÑA N°3', proveedor: 'Laurita', categoria: 'Empaque y bases', caja: 1, precio_caja: 18.5, precio_unitario: 18.5 },
  { cod: 'GAL-01', nombre: 'PRINGLES ORIGINAL 37GR', proveedor: 'Grazy', categoria: 'Galletas y snacks', caja: 12, precio_caja: 48.48, precio_unitario: 4.04 },
  { cod: 'GAL-02', nombre: 'TOSTADAS ORIGINAL BAUDUCCO 142 GR', proveedor: 'Grazy', categoria: 'Galletas y snacks', caja: 36, precio_caja: 186, precio_unitario: 5.17 },
  { cod: 'GAL-03', nombre: 'WAFER FRESA BAUDUCCO 14O GR', proveedor: 'Grazy', categoria: 'Galletas y snacks', caja: 24, precio_caja: 72.5, precio_unitario: 3.02 },
  { cod: 'GAL-04', nombre: 'COOKIES ORIGINAL BAUDUCCO', proveedor: 'Grazy', categoria: 'Galletas y snacks', caja: 24, precio_caja: 54.5, precio_unitario: 2.27 },
  { cod: 'GAL-05', nombre: 'CEREAL ANGEL AVENA 120GR', proveedor: 'Grazy', categoria: 'Galletas y snacks', caja: 30, precio_caja: 74.5, precio_unitario: 2.48 },
  { cod: 'GAL-06', nombre: 'CHOCODONUTS COSTA 204GR', proveedor: 'Grazy', categoria: 'Galletas y snacks', caja: 16, precio_caja: 108, precio_unitario: 6.75 },
  { cod: 'GOU-01', nombre: 'ACEITUNAS VERDES RELLENAS CON CASTAÑAS 340GR', proveedor: 'Maras', categoria: 'Gourmet', caja: 18, precio_caja: 219.6, precio_unitario: 12.2 },
  { cod: 'GOU-02', nombre: 'PICADILLO DE ACEITUNAS VERDES FRASCO 220GR', proveedor: 'Maras', categoria: 'Gourmet', caja: 18, precio_caja: 219.6, precio_unitario: 12.2 },
  { cod: 'GOU-03', nombre: 'PRETZEL ARTESANAL CAJA 110GR', proveedor: 'Maras', categoria: 'Gourmet', caja: 24, precio_caja: 169.2, precio_unitario: 7.05 },
  { cod: 'GOU-04', nombre: 'PRETZEL ARTESANAL BOLSA 50GR', proveedor: 'Maras', categoria: 'Gourmet', caja: 48, precio_caja: 201.6, precio_unitario: 4.2 },
  { cod: 'LAC-01', nombre: 'MEZCLA LACTEA IDEAL AMANECER 390GR', proveedor: 'Grazy', categoria: 'Lácteos', caja: 24, precio_caja: 68, precio_unitario: 2.83 },
  { cod: 'LAC-02', nombre: 'MEZCLA LACTEA IDEAL CREMOSITA 390GR', proveedor: 'Grazy', categoria: 'Lácteos', caja: 24, precio_caja: 83.3, precio_unitario: 3.47 },
  { cod: 'PAN-01', nombre: 'PANETON DONOFRIO BOLSA 880GR', proveedor: 'Grazy', categoria: 'Panetones', caja: 6, precio_caja: 136, precio_unitario: 22.67 },
  { cod: 'PAN-02', nombre: 'PANETON BLANCA FLOR BOLSA 900GR', proveedor: 'Grazy', categoria: 'Panetones', caja: 6, precio_caja: 127, precio_unitario: 21.17 },
  { cod: 'PAN-04', nombre: 'PANETON BUON NATALE BOLSA 800GR', proveedor: 'Grazy', categoria: 'Panetones', caja: 6, precio_caja: 100, precio_unitario: 16.67 },
  { cod: 'PAN-05', nombre: 'PANETON BUON NATALE CAJA 800GR', proveedor: 'Grazy', categoria: 'Panetones', caja: 6, precio_caja: 111.5, precio_unitario: 18.58 },
  { cod: 'PAN-06', nombre: 'PANETON SAYON BOLSA 750GR', proveedor: 'Grazy', categoria: 'Panetones', caja: 6, precio_caja: 90, precio_unitario: 15 },
  { cod: 'PAN-07', nombre: 'PANETON DONOFRIO CAJA 880GR', proveedor: 'Grazy', categoria: 'Panetones', caja: 6, precio_caja: 150, precio_unitario: 25 },
  { cod: 'VIN-01', nombre: 'ESPUMANTE RICCADONNA ASTI 750ML', proveedor: 'The Shinka', categoria: 'Vinos y espumantes', caja: 6, precio_caja: 270, precio_unitario: 45 },
  { cod: 'VIN-02', nombre: 'ESPUMANTE SANTIAGO QUEIROLO PRIMADO 750ML', proveedor: 'The Shinka', categoria: 'Vinos y espumantes', caja: 12, precio_caja: 130, precio_unitario: 10.83 },
  { cod: 'VIN-03', nombre: 'ESPUMOSO MAGNOLIA SEMI SECO TACAMA 750 ML', proveedor: 'Perufarma', categoria: 'Vinos y espumantes', caja: 12, precio_caja: 397.2, precio_unitario: 33.1 },
  { cod: 'VIN-04', nombre: 'TRAPICHE ASTICA CABERNET SAUVIGNON MALBEC 750ML', proveedor: 'Perufarma', categoria: 'Vinos y espumantes', caja: 12, precio_caja: 266.4, precio_unitario: 22.2 },
  { cod: 'VIN-05', nombre: 'COLECCIÓN PRIVADA MALBEC X 750 ML', proveedor: 'Perufarma', categoria: 'Vinos y espumantes', caja: 6, precio_caja: 253.2, precio_unitario: 42.2 },
];

// Hoja CAJAS del Excel: cuántos productos entran en cada caja y sus medidas
// (largo x ancho x alto, en cm).
const CAJAS: Record<string, { capacidad: number | null; medidas: string }> = {
  'EMP-01': { capacidad: 25, medidas: '36.5 x 24.1 x 30.5' },
  'EMP-02': { capacidad: 25, medidas: '36.5 x 24.1 x 30.5' },
  'EMP-03': { capacidad: 35, medidas: '37 x 24.4 x 34.6' },
  'EMP-04': { capacidad: 35, medidas: '39 x 29.5 x 23' },
  'EMP-05': { capacidad: 40, medidas: '42 x 32 x 31.5' },
  'EMP-06': { capacidad: null, medidas: '49 x 32 x 25' },
  'EMP-07': { capacidad: null, medidas: '45 x 34 x 44.3' },
  'EMP-08': { capacidad: null, medidas: '40 x 29.6 x 49' },
  'EMP-09': { capacidad: null, medidas: '51.2 x 55.3 x 29.5' },
  'EMP-10': { capacidad: null, medidas: '41 x 28.5 x 22.5' },
  'EMP-11': { capacidad: null, medidas: '48 x 35 x 26' },
};

export const CATALOGO_BASE = PRODUCTOS.map((p) => ({
  ...p,
  capacidad: CAJAS[p.cod]?.capacidad ?? null,
  medidas: CAJAS[p.cod]?.medidas ?? null,
}));
