export const CATALOGO_BASE = [
  { cod: "PAN-01", nombre: "PANETON DONOFRIO BOLSA 880GR", proveedor: "Grazy", categoria: "Panetones", caja: 6, precio_caja: 136.5, precio_unitario: 22.75 },
  { cod: "PAN-02", nombre: "PANETON BLANCA FLOR BOLSA 900GR", proveedor: "Katty", categoria: "Panetones", caja: 6, precio_caja: 107.0, precio_unitario: 17.83 },
  { cod: "PAN-03", nombre: "PANETON SAN JORGE CAJA 900GR", proveedor: "Grazy", categoria: "Panetones", caja: 6, precio_caja: 130.0, precio_unitario: 21.67 },
  { cod: "PAN-04", nombre: "PANETON BUON NATALE BOLSA 750GR", proveedor: "Grazy", categoria: "Panetones", caja: 6, precio_caja: 111.5, precio_unitario: 18.58 },
  { cod: "PAN-05", nombre: "PANETON BUON NATALE CAJA 750GR", proveedor: "Grazy", categoria: "Panetones", caja: 6, precio_caja: 122.5, precio_unitario: 20.42 },
  { cod: "PAN-06", nombre: "PANETON SAYON BOLSA 750GR", proveedor: "Grazy", categoria: "Panetones", caja: 6, precio_caja: 91.0, precio_unitario: 15.17 },
  { cod: "PAN-07", nombre: "PANETON PYC BOLSA 800GR", proveedor: "BIMBO", categoria: "Panetones", caja: 6, precio_caja: 73.99, precio_unitario: 12.33 },
  { cod: "PAN-08", nombre: "PANETON BIMBO PREMIUM CAJA 900GR", proveedor: "BIMBO", categoria: "Panetones", caja: 6, precio_caja: 113.99, precio_unitario: 19.0 },
  { cod: "PAN-09", nombre: "PANETON BIMBO BOLSA 900GR", proveedor: "BIMBO", categoria: "Panetones", caja: 6, precio_caja: 110.0, precio_unitario: 18.33 },
  { cod: "PAN-10", nombre: "PANETON BAUDUCCO CAJA 900GR", proveedor: "Bauducco", categoria: "Panetones", caja: 6, precio_caja: 156.0, precio_unitario: 26.0 },
  { cod: "PAN-11", nombre: "PANETON BAUDUCCO CAJA 680GR", proveedor: "Bauducco", categoria: "Panetones", caja: 6, precio_caja: 141.0, precio_unitario: 23.5 },
  { cod: "VIN-01", nombre: "ESPUMANTE RICCADONNA ASTI 750ML", proveedor: "The Shinka", categoria: "Vinos y espumantes", caja: 6, precio_caja: 255.0, precio_unitario: 42.5 },
  { cod: "VIN-02", nombre: "ESPUMANTE SANTIAGO QUEIROLO PRIMADO 750ML", proveedor: "The Shinka", categoria: "Vinos y espumantes", caja: 12, precio_caja: 130.0, precio_unitario: 10.83 },
  { cod: "VIN-03", nombre: "VINO TINTO SEMI SECO TACAMA X 750", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 12, precio_caja: 157.8, precio_unitario: 13.15 },
  { cod: "VIN-04", nombre: "ESPUMANTE SANTERO ASTI 750ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 6, precio_caja: 210.0, precio_unitario: 35.0 },
  { cod: "VIN-05", nombre: "HMR RESERVA + TUBO X 750ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 1, precio_caja: 80.0, precio_unitario: 80.0 },
  { cod: "VIN-06", nombre: "PROTOS CRIANZA PACK X1 BOT X750ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 1, precio_caja: 50.0, precio_unitario: 50.0 },
  { cod: "VIN-07", nombre: "LA MASCOTA MALBEC X 750 ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 1, precio_caja: 39.81, precio_unitario: 39.81 },
  { cod: "VIN-08", nombre: "COLECCION PRIVADA MALBEC X 750 ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 1, precio_caja: 32.88, precio_unitario: 32.88 },
  { cod: "VIN-09", nombre: "VINO BLANCO MALAMIGO LADY DRAMA 750ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 1, precio_caja: 23.09, precio_unitario: 23.09 },
  { cod: "VIN-10", nombre: "MARQUES DE RISCAL ROSADO X 750 ML", proveedor: "Perufarma", categoria: "Vinos y espumantes", caja: 1, precio_caja: 38.82, precio_unitario: 38.82 },
  { cod: "LIC-01", nombre: "PISCO FERREYROS PURO QUEBRANTA X 750 ML", proveedor: "Perufarma", categoria: "Licores", caja: 1, precio_caja: 87.31, precio_unitario: 87.31 },
  { cod: "LIC-02", nombre: "PISCO PURO QUEBRANTA HERMANO 700 ML", proveedor: "Perufarma", categoria: "Licores", caja: 1, precio_caja: 23.35, precio_unitario: 23.35 },
  { cod: "CHO-01", nombre: "FERRERO ROCHER T4", proveedor: "Grazy", categoria: "Chocolates y dulces", caja: 10, precio_caja: 95.5, precio_unitario: 9.55 },
  { cod: "CHO-02", nombre: "HERSHEY DOYBAG NUGGET 120GR", proveedor: "Grazy", categoria: "Chocolates y dulces", caja: 12, precio_caja: 172.5, precio_unitario: 14.38 },
  { cod: "CHO-03", nombre: "BOTA NAVIDENA M&M 140GR", proveedor: "Perufarma", categoria: "Chocolates y dulces", caja: 12, precio_caja: 98.16, precio_unitario: 8.18 },
  { cod: "CHO-04", nombre: "CALENDARIO ADVIENTO M&M/SNICKERS", proveedor: "Perufarma", categoria: "Chocolates y dulces", caja: 8, precio_caja: 401.2, precio_unitario: 50.15 },
  { cod: "CHO-05", nombre: "NOEL DE CHOCOLATE LA IBERICA 60GR", proveedor: "La Iberica", categoria: "Chocolates y dulces", caja: 1, precio_caja: 14.0, precio_unitario: 14.0 },
  { cod: "CHO-06", nombre: "TOFFEES SURTIDOS LA IBERICA 100GR", proveedor: "La Iberica", categoria: "Chocolates y dulces", caja: 1, precio_caja: 7.79, precio_unitario: 7.79 },
  { cod: "GAL-01", nombre: "PRINGLES ORIGINAL 37GR", proveedor: "Grazy", categoria: "Galletas y snacks", caja: 12, precio_caja: 47.5, precio_unitario: 3.96 },
  { cod: "GAL-02", nombre: "TOSTADAS ORIGINAL BAUDUCCO", proveedor: "Katty", categoria: "Galletas y snacks", caja: 36, precio_caja: 0, precio_unitario: 4.8 },
  { cod: "GAL-03", nombre: "WAFER FRESA BAUDUCCO", proveedor: "Grazy", categoria: "Galletas y snacks", caja: 24, precio_caja: 44.5, precio_unitario: 1.85 },
  { cod: "GAL-04", nombre: "COOKIES ORIGINAL BAUDUCCO", proveedor: "Grazy", categoria: "Galletas y snacks", caja: 24, precio_caja: 53.5, precio_unitario: 2.23 },
  { cod: "ABA-01", nombre: "CHOCOLATE DE TAZA ORO DE CUSCO 90GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 72, precio_caja: 61.5, precio_unitario: 0.85 },
  { cod: "ABA-02", nombre: "ARROZ COSTENO EXTRA GRANEADO 750GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 20, precio_caja: 71.0, precio_unitario: 3.55 },
  { cod: "ABA-03", nombre: "AZUCAR DULFINA 1KG", proveedor: "Grazy", categoria: "Abarrotes", caja: 10, precio_caja: 33.0, precio_unitario: 3.3 },
  { cod: "ABA-04", nombre: "ACEITE PRIMOR 900ML", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 95.5, precio_unitario: 7.96 },
  { cod: "ABA-05", nombre: "ACEITE CIL 900 ML", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 81.2, precio_unitario: 6.77 },
  { cod: "ABA-06", nombre: "LENTEJA COSTENO 500GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 81.0, precio_unitario: 6.75 },
  { cod: "ABA-07", nombre: "LENTEJON COSTENO 500GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 68.0, precio_unitario: 5.67 },
  { cod: "ABA-08", nombre: "ARVEJA PARTIDA COSTENO 500GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 36.5, precio_unitario: 3.04 },
  { cod: "ABA-09", nombre: "FIDEO NICOLINI SOPAS 225GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 20, precio_caja: 20.5, precio_unitario: 1.03 },
  { cod: "ABA-10", nombre: "FIDEO NICOLINI SPAGUETTI 450GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 20, precio_caja: 39.0, precio_unitario: 1.95 },
  { cod: "ABA-11", nombre: "MERMELADA DE FRESA FANNY 90GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 108, precio_caja: 141.6, precio_unitario: 1.31 },
  { cod: "ABA-12", nombre: "MERMELADA DE FRESA FANNY 227GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 40.6, precio_unitario: 3.38 },
  { cod: "ABA-13", nombre: "AVENA 3 OSITOS 100GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 24, precio_caja: 16.2, precio_unitario: 0.68 },
  { cod: "ABA-14", nombre: "CACAO 100% DE TAZA SOL DEL CUSCO", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 115.5, precio_unitario: 9.63 },
  { cod: "ABA-15", nombre: "ARROZ PAISANA 1KG", proveedor: "Grazy", categoria: "Abarrotes", caja: 12, precio_caja: 56.0, precio_unitario: 4.67 },
  { cod: "ABA-16", nombre: "CHOCOLATE DE TAZA SOL DEL CUSCO 90GR", proveedor: "Grazy", categoria: "Abarrotes", caja: 72, precio_caja: 147.0, precio_unitario: 2.04 },
  { cod: "CON-01", nombre: "ATUN FILETE FLORIDA 140GR", proveedor: "Grazy", categoria: "Conservas", caja: 48, precio_caja: 224.5, precio_unitario: 4.68 },
  { cod: "CON-02", nombre: "ATUN FILETE PRIMOR 140GR", proveedor: "Grazy", categoria: "Conservas", caja: 48, precio_caja: 210.0, precio_unitario: 4.38 },
  { cod: "CON-03", nombre: "TROZOS DE ATUN PRIMOR 140GR", proveedor: "Grazy", categoria: "Conservas", caja: 48, precio_caja: 196.5, precio_unitario: 4.09 },
  { cod: "CON-04", nombre: "DURAZNO ACONCAGUA 822GR", proveedor: "Grazy", categoria: "Conservas", caja: 12, precio_caja: 97.5, precio_unitario: 8.13 },
  { cod: "CON-05", nombre: "DURAZNO ARICA 820GR", proveedor: "Grazy", categoria: "Conservas", caja: 12, precio_caja: 73.0, precio_unitario: 6.08 },
  { cod: "CON-06", nombre: "DURAZNO COMPAS 820GR", proveedor: "Grazy", categoria: "Conservas", caja: 12, precio_caja: 77.5, precio_unitario: 6.46 },
  { cod: "LAC-01", nombre: "MEZCLA LACTEA IDEAL AMANECER 390GR", proveedor: "Grazy", categoria: "Lácteos", caja: 24, precio_caja: 70.0, precio_unitario: 2.92 },
  { cod: "LAC-02", nombre: "MEZCLA LACTEA IDEAL CREMOSITA 390GR", proveedor: "Grazy", categoria: "Lácteos", caja: 24, precio_caja: 85.0, precio_unitario: 3.54 },
  { cod: "LAC-03", nombre: "GLORIA DESLACTOSADA 390GR", proveedor: "Grazy", categoria: "Lácteos", caja: 24, precio_caja: 90.0, precio_unitario: 3.75 },
  { cod: "LAC-04", nombre: "LECHE RECONSTITUIDA GLORIA LATA 390GR", proveedor: "Grazy", categoria: "Lácteos", caja: 24, precio_caja: 86.5, precio_unitario: 3.6 },
  { cod: "GOU-01", nombre: "MOLEDOR SAL DE MARAS CON ESPECIAS 100GR", proveedor: "Maras", categoria: "Gourmet", caja: 24, precio_caja: 328.51, precio_unitario: 13.69 },
  { cod: "GOU-02", nombre: "ACEITUNAS VERDES RELLENAS CON CASTANAS 340GR", proveedor: "Maras", categoria: "Gourmet", caja: 18, precio_caja: 218.77, precio_unitario: 12.15 },
  { cod: "GOU-03", nombre: "PICADILLO DE ACEITUNAS VERDES FRASCO 220GR", proveedor: "Maras", categoria: "Gourmet", caja: 18, precio_caja: 218.77, precio_unitario: 12.15 },
  { cod: "GOU-04", nombre: "PRETZEL ARTESANAL CAJA 110GR", proveedor: "Maras", categoria: "Gourmet", caja: 24, precio_caja: 160.57, precio_unitario: 6.69 },
  { cod: "EMP-01", nombre: "CAJA DE CARTON 1 CON PRECINTO", proveedor: "Laurita", categoria: "Empaque y bases", caja: 1, precio_caja: 4.2, precio_unitario: 4.2 },
  { cod: "EMP-02", nombre: "CAJA DE CARTON 2 CON PRECINTO", proveedor: "Laurita", categoria: "Empaque y bases", caja: 1, precio_caja: 3.5, precio_unitario: 3.5 },
  { cod: "EMP-03", nombre: "CAJA DE CARTON 3 CON PRECINTO", proveedor: "Laurita", categoria: "Empaque y bases", caja: 1, precio_caja: 4.2, precio_unitario: 4.2 },
  { cod: "EMP-04", nombre: "CAJA DE CARTON 4 CON PRECINTO", proveedor: "Laurita", categoria: "Empaque y bases", caja: 1, precio_caja: 6.9, precio_unitario: 6.9 },
  { cod: "EMP-05", nombre: "TINA", proveedor: "Laurita", categoria: "Empaque y bases", caja: 1, precio_caja: 2.8, precio_unitario: 2.8 },
  { cod: "EMP-06", nombre: "CELOFAN + LAZO", proveedor: "Laurita", categoria: "Empaque y bases", caja: 1, precio_caja: 1.5, precio_unitario: 1.5 },
  { cod: "EMP-07", nombre: "BASE MADERA", proveedor: "Surquillo", categoria: "Empaque y bases", caja: 1, precio_caja: 8.0, precio_unitario: 8.0 },
  { cod: "EMP-08", nombre: "BASE CARTON", proveedor: "Surquillo", categoria: "Empaque y bases", caja: 1, precio_caja: 4.5, precio_unitario: 4.5 },
  { cod: "EMP-09", nombre: "CESTO", proveedor: "Surquillo", categoria: "Empaque y bases", caja: 1, precio_caja: 15.0, precio_unitario: 15.0 },
  { cod: "EMP-10", nombre: "CAJA", proveedor: "Surquillo", categoria: "Empaque y bases", caja: 1, precio_caja: 11.0, precio_unitario: 11.0 },
];
