export type PlantillaItem = { cod: string; cantidad: number };

export type Plantilla = {
  codigo: string;
  nombre: string;
  nivel: string;
  items: PlantillaItem[];
};

export const PLANTILLAS: Plantilla[] = [
  {
    codigo: "N1-01",
    nombre: "Luz de Navidad",
    nivel: "N1",
    items: [
      { cod: "PAN-06", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-01", cantidad: 1 },
      { cod: "LAC-01", cantidad: 1 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "GAL-05", cantidad: 1 },
      { cod: "EMP-01", cantidad: 1 },
    ],
  },
  {
    codigo: "N1-02",
    nombre: "Tradición Navideña",
    nivel: "N1",
    items: [
      { cod: "PAN-04", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-01", cantidad: 1 },
      { cod: "LAC-01", cantidad: 1 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "GAL-05", cantidad: 1 },
      { cod: "ABA-10", cantidad: 1 },
      { cod: "EMP-01", cantidad: 1 },
    ],
  },
  {
    codigo: "N2-01",
    nombre: "Encuentro Navideño",
    nivel: "N2",
    items: [
      { cod: "PAN-04", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-01", cantidad: 1 },
      { cod: "LAC-01", cantidad: 1 },
      { cod: "ABA-09", cantidad: 1 },
      { cod: "ABA-08", cantidad: 1 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "CON-02", cantidad: 1 },
      { cod: "CON-04", cantidad: 1 },
      { cod: "EMP-01", cantidad: 1 },
    ],
  },
  {
    codigo: "N2-02",
    nombre: "Celebración Navideña",
    nivel: "N2",
    items: [
      { cod: "PAN-05", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-05", cantidad: 1 },
      { cod: "ABA-01", cantidad: 1 },
      { cod: "LAC-01", cantidad: 1 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-12", cantidad: 2 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "CON-02", cantidad: 1 },
      { cod: "VIN-02", cantidad: 1 },
      { cod: "EMP-03", cantidad: 1 },
    ],
  },
  {
    codigo: "N2-03",
    nombre: "Hogar Navideño",
    nivel: "N2",
    items: [
      { cod: "PAN-01", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 1 },
      { cod: "LAC-01", cantidad: 1 },
      { cod: "ABA-08", cantidad: 1 },
      { cod: "ABA-09", cantidad: 1 },
      { cod: "ABA-07", cantidad: 1 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-02", cantidad: 1 },
      { cod: "CON-04", cantidad: 1 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "EMP-03", cantidad: 1 },
    ],
  },
  {
    codigo: "N3-01",
    nombre: "Nochebuena Reserva",
    nivel: "N3",
    items: [
      { cod: "PAN-05", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 1 },
      { cod: "LAC-01", cantidad: 1 },
      { cod: "ABA-08", cantidad: 1 },
      { cod: "ABA-09", cantidad: 1 },
      { cod: "ABA-07", cantidad: 1 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-01", cantidad: 1 },
      { cod: "CON-03", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "ABA-12", cantidad: 2 },
      { cod: "VIN-04", cantidad: 1 },
      { cod: "EMP-03", cantidad: 1 },
    ],
  },
  {
    codigo: "N3-02",
    nombre: "Cena Familiar",
    nivel: "N3",
    items: [
      { cod: "PAN-01", cantidad: 1 },
      { cod: "ABA-02", cantidad: 2 },
      { cod: "ABA-03", cantidad: 2 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 2 },
      { cod: "LAC-01", cantidad: 2 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-09", cantidad: 2 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-01", cantidad: 2 },
      { cod: "CON-03", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "ABA-12", cantidad: 3 },
      { cod: "CHO-01", cantidad: 1 },
      { cod: "EMP-04", cantidad: 1 },
    ],
  },
  {
    codigo: "N3-03",
    nombre: "Brindis de Oro",
    nivel: "N3",
    items: [
      { cod: "PAN-01", cantidad: 1 },
      { cod: "ABA-02", cantidad: 1 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 2 },
      { cod: "LAC-01", cantidad: 2 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-09", cantidad: 1 },
      { cod: "ABA-07", cantidad: 1 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-01", cantidad: 1 },
      { cod: "CON-03", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "VIN-03", cantidad: 1 },
      { cod: "EMP-04", cantidad: 1 },
    ],
  },
  {
    codigo: "N4-01",
    nombre: "Estrella de Belén",
    nivel: "N4",
    items: [
      { cod: "PAN-01", cantidad: 1 },
      { cod: "ABA-02", cantidad: 2 },
      { cod: "ABA-03", cantidad: 1 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 2 },
      { cod: "LAC-01", cantidad: 2 },
      { cod: "ABA-08", cantidad: 1 },
      { cod: "ABA-09", cantidad: 1 },
      { cod: "ABA-07", cantidad: 1 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-01", cantidad: 1 },
      { cod: "CON-03", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "CHO-05", cantidad: 1 },
      { cod: "VIN-05", cantidad: 1 },
      { cod: "EMP-04", cantidad: 1 },
    ],
  },
  {
    codigo: "N4-02",
    nombre: "Gala de Nochebuena",
    nivel: "N4",
    items: [
      { cod: "PAN-07", cantidad: 1 },
      { cod: "ABA-02", cantidad: 2 },
      { cod: "ABA-03", cantidad: 2 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 2 },
      { cod: "LAC-01", cantidad: 2 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-09", cantidad: 1 },
      { cod: "ABA-07", cantidad: 1 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-01", cantidad: 2 },
      { cod: "CON-03", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "ABA-12", cantidad: 1 },
      { cod: "GAL-02", cantidad: 1 },
      { cod: "CHO-01", cantidad: 1 },
      { cod: "CHO-05", cantidad: 1 },
      { cod: "CHO-07", cantidad: 1 },
      { cod: "GOU-04", cantidad: 1 },
      { cod: "VIN-01", cantidad: 1 },
      { cod: "EMP-05", cantidad: 1 },
    ],
  },
  {
    codigo: "N4-03",
    nombre: "Gran Reserva Navideña",
    nivel: "N4",
    items: [
      { cod: "PAN-07", cantidad: 1 },
      { cod: "ABA-02", cantidad: 2 },
      { cod: "ABA-03", cantidad: 2 },
      { cod: "ABA-04", cantidad: 1 },
      { cod: "ABA-01", cantidad: 3 },
      { cod: "LAC-01", cantidad: 3 },
      { cod: "ABA-08", cantidad: 2 },
      { cod: "ABA-09", cantidad: 2 },
      { cod: "ABA-07", cantidad: 1 },
      { cod: "ABA-06", cantidad: 1 },
      { cod: "CON-01", cantidad: 2 },
      { cod: "CON-03", cantidad: 1 },
      { cod: "ABA-17", cantidad: 1 },
      { cod: "ABA-12", cantidad: 2 },
      { cod: "GAL-02", cantidad: 1 },
      { cod: "GAL-04", cantidad: 1 },
      { cod: "CHO-03", cantidad: 1 },
      { cod: "CHO-08", cantidad: 1 },
      { cod: "CHO-05", cantidad: 1 },
      { cod: "GOU-02", cantidad: 1 },
      { cod: "GOU-03", cantidad: 1 },
      { cod: "VIN-01", cantidad: 1 },
      { cod: "EMP-05", cantidad: 1 },
    ],
  },
];

export function plantillaPorCodigo(codigo: string): Plantilla | undefined {
  return PLANTILLAS.find((p) => p.codigo === codigo);
}
